const  brandsJson = [
  { label: "A. Lange & Söhne", value:  1},
  { label: "ABP Paris", value:  2},
  { label: "AD-Chronographen", value:  3},
  { label: "Aerowatch", value:  4},
  { label: "Aigle", value:  5},
  { label: "Aigner", value:  6},
  { label: "Alain Silberstein", value:  7},
  { label: "Alexander Shorokhoff", value:  8},
  { label: "Alfred Dunhill", value:  9},
  { label: "Alfred Rochat & Fils", value:  10},
  { label: "Alpina", value:  11},
  { label: "Andersen Genève", value:  12},
  { label: "Angelus", value:  13},
  { label: "Angular Momentum", value:  14},
  { label: "Anonimo", value:  15},
  { label: "Apple", value:  16},
  { label: "Aquanautic", value:  17},
  { label: "Aquastar", value:  18},
  { label: "Aristo", value:  19},
  { label: "Armand Nicolet", value:  20},
  { label: "Armani", value:  21},
  { label: "Armin Strom", value:  22},
  { label: "Arnold & Son", value:  23},
  { label: "Artisanal", value:  24},
  { label: "Artya", value:  25},
  { label: "Askania", value:  26},
  { label: "Ateliers deMonaco", value:  27},
  { label: "Atlantic", value:  28},
  { label: "Audemars Piguet", value:  29},
  { label: "Auguste Reymond", value:  30},
  { label: "Auricoste", value:  31},
  { label: "Avier", value:  32},
  { label: "Azimuth", value:  33},
  { label: "Azzaro", value:  34},
  { label: "B.R.M", value:  35},
  { label: "Ball", value:  36},
  { label: "Balmain", value:  37},
  { label: "Barington", value:  38},
  { label: "Baume & Mercier", value:  39},
  { label: "Bedat & Co", value:  40},
  { label: "Bell & Ross", value:  41},
  { label: "Benrus", value:  42},
  { label: "Benzinger", value:  43},
  { label: "Berne", value:  44},
  { label: "Bertolucci", value:  45},
  { label: "Beuchat", value:  46},
  { label: "Bifora", value:  47},
  { label: "Black-Out Concept", value:  48},
  { label: "Blancier", value:  49},
  { label: "Blancpain", value:  50},
  { label: "blu", value:  51},
  { label: "Boegli", value:  52},
  { label: "Bogner Time", value:  53},
  { label: "Bomberg", value:  54},
  { label: "Boucheron", value:  55},
  { label: "Bovet", value:  56},
  { label: "Breguet", value:  57},
  { label: "Breil", value:  58},
  { label: "Breitling", value:  59},
  { label: "Bremont", value:  60},
  { label: "Bruno Söhnle", value:  61},
  { label: "Bulgari", value:  62},
  { label: "Bulova", value:  63},
  { label: "Bunz", value:  64},
  { label: "Burberry", value:  65},
  { label: "BWC-Swiss", value:  66},
  { label: "C.H. Wolf", value:  67},
  { label: "Cabestan", value:  68},
  { label: "Camel Active", value:  69},
  { label: "Camille Fournet", value:  70},
  { label: "Candino", value:  71},
  { label: "Carl F. Bucherer", value:  72},
  { label: "Carlo Ferrara", value:  73},
  { label: "Cartier", value:  74},
  { label: "Casio", value:  75},
  { label: "Catamaran", value:  76},
  { label: "Catena", value:  77},
  { label: "Catorex", value:  78},
  { label: "Cattin", value:  79},
  { label: "Century", value:  80},
  { label: "Cerruti", value:  81},
  { label: "Certina", value:  82},
  { label: "Chanel", value:  83},
  { label: "Charmex", value:  84},
  { label: "Charriol", value:  85},
  { label: "Chase-Durer", value:  86},
  { label: "Chaumet", value:  87},
  { label: "Chopard", value:  88},
  { label: "Chris Benz", value:  89},
  { label: "Christiaan v.d. Klaauw", value:  90},
  { label: "Christophe Claret", value:  91},
  { label: "Chronographe Suisse Cie", value:  92},
  { label: "Chronoswiss", value:  93},
  { label: "Churpfälzische Uhrenmanufaktur", value:  94},
  { label: "Citizen", value:  95},
  { label: "ck Calvin Klein", value:  96},
  { label: "Claude Meylan", value:  97},
  { label: "Clerc", value:  98},
  { label: "Concord", value:  99},
  { label: "Condor", value:  100},
  { label: "Cornehl", value:  101},
  { label: "Cortébert", value:  102},
  { label: "Corum", value:  103},
  { label: "Creo", value:  104},
  { label: "Cuervo y Sobrinos", value:  105},
  { label: "Cvstos", value:  106},
  { label: "CWC", value:  107},
  { label: "Cyclos", value:  108},
  { label: "Cyma", value:  109},
  { label: "Cyrus", value:  110},
  { label: "D.Dornblüth & Sohn", value:  111},
  { label: "Damasko", value:  112},
  { label: "Daniel Roth", value:  113},
  { label: "Davidoff", value:  114},
  { label: "Davosa", value:  115},
  { label: "De Bethune", value:  116},
  { label: "De Grisogono", value:  117},
  { label: "Deep Blue", value:  118},
  { label: "DeLaCour", value:  119},
  { label: "DeLaneau", value:  120},
  { label: "Delma", value:  121},
  { label: "Devon", value:  122},
  { label: "Dewitt", value:  123},
  { label: "Diesel", value:  124},
  { label: "Dietrich", value:  125},
  { label: "Dior", value:  126},
  { label: "Dodane", value:  127},
  { label: "Dolce & Gabbana", value:  128},
  { label: "Doxa", value:  129},
  { label: "Dubey & Schaldenbrand", value:  130},
  { label: "DuBois 1785", value:  131},
  { label: "DuBois et fils", value:  132},
  { label: "Dufeau", value:  133},
  { label: "Dugena", value:  134},
  { label: "Dürmeister", value:  135},
  { label: "Ebel", value:  136},
  { label: "Eberhard & Co.", value:  137},
  { label: "Edox", value:  138},
  { label: "Eichmüller", value:  139},
  { label: "Election", value:  140},
  { label: "Elgin", value:  141},
  { label: "Elysee", value:  142},
  { label: "Enicar", value:  143},
  { label: "Ennebi", value:  144},
  { label: "Epos", value:  145},
  { label: "Ernest Borel", value:  146},
  { label: "Ernst Benz", value:  147},
  { label: "Erwin Sattler", value:  148},
  { label: "Esprit", value:  149},
  { label: "Eterna", value:  150},
  { label: "Eulit", value:  151},
  { label: "Eulux", value:  152},
  { label: "F.P.Journe", value:  153},
  { label: "Fabergé", value:  154},
  { label: "Favre-Leuba", value:  155},
  { label: "Fendi", value:  156},
  { label: "Festina", value:  157},
  { label: "Flik Flak", value:  158},
  { label: "Fluco", value:  159},
  { label: "Fludo", value:  160},
  { label: "Formex", value:  161},
  { label: "Fortis", value:  162},
  { label: "Fossil", value:  163},
  { label: "Franc Vila", value:  164},
  { label: "Franck Dubarry", value:  165},
  { label: "Franck Muller", value:  166},
  { label: "Frederique Constant", value:  167},
  { label: "Gaga Milano", value:  168},
  { label: "Gallet", value:  169},
  { label: "Gant", value:  170},
  { label: "Gardé", value:  171},
  { label: "Garmin", value:  172},
  { label: "Georges V", value:  173},
  { label: "Germano & Walter", value:  174},
  { label: "Gevril", value:  175},
  { label: "Girard Perregaux", value:  176},
  { label: "Giuliano Mazzuoli", value:  177},
  { label: "Glashütte Original", value:  178},
  { label: "Glycine", value:  179},
  { label: "Graf", value:  180},
  { label: "Graham", value:  181},
  { label: "Greubel Forsey", value:  182},
  { label: "Grovana", value:  183},
  { label: "Gruen", value:  184},
  { label: "Grönefeld", value:  185},
  { label: "GUB Glashütte", value:  186},
  { label: "Gucci", value:  187},
  { label: "Guess", value:  188},
  { label: "Gérald Genta", value:  189},
  { label: "Gübelin", value:  190},
  { label: "H.I.D. Watch", value:  191},
  { label: "H.Moser & Cie.", value:  192},
  { label: "Habring²", value:  193},
  { label: "Hacher", value:  194},
  { label: "Haemmer", value:  195},
  { label: "Hamilton", value:  196},
  { label: "Hanhart", value:  197},
  { label: "Harry Winston", value:  198},
  { label: "Hautlence", value:  199},
  { label: "HD3", value:  200},
  { label: "Hebdomas", value:  201},
  { label: "Hebe", value:  202},
  { label: "Hentschel Hamburg", value:  203},
  { label: "Hermès", value:  204},
  { label: "Herzog", value:  205},
  { label: "Heuer", value:  206},
  { label: "Hirsch", value:  207},
  { label: "Hublot", value:  208},
  { label: "Hugo Boss", value:  209},
  { label: "HYT", value:  210},
  { label: "Ice Watch", value:  211},
  { label: "Ikepod", value:  212},
  { label: "Illinois", value:  213},
  { label: "Ingersoll", value:  214},
  { label: "Invicta", value:  215},
  { label: "Itay Noy", value:  216},
  { label: "IWC", value:  217},
  { label: "Jacob & Co.", value:  218},
  { label: "Jacques Etoile", value:  219},
  { label: "Jacques Lemans", value:  220},
  { label: "Jaeger-LeCoultre", value:  221},
  { label: "Jaermann & Stübi", value:  222},
  { label: "Jaquet-Droz", value:  223},
  { label: "JB Gioacchino", value:  224},
  { label: "Jean d'Eve", value:  225},
  { label: "Jean Lassale", value:  226},
  { label: "Jean Marcel", value:  227},
  { label: "JeanRichard", value:  228},
  { label: "Joop", value:  229},
  { label: "Jorg Hysek", value:  230},
  { label: "Jules Jürgensen", value:  231},
  { label: "Junghans", value:  232},
  { label: "Junkers", value:  233},
  { label: "Juvenia", value:  234},
  { label: "Kelek", value:  235},
  { label: "KHS", value:  236},
  { label: "KHS-Watch", value:  237},
  { label: "Kienzle", value:  238},
  { label: "Kobold", value:  239},
  { label: "Konstantin Chaykin", value:  240},
  { label: "Korloff", value:  241},
  { label: "Krieger", value:  242},
  { label: "Kronsegler", value:  243},
  { label: "L'Epée", value:  244},
  { label: "L.Leroy", value:  245},
  { label: "Laco", value:  246},
  { label: "Lacoste", value:  247},
  { label: "Lancaster", value:  248},
  { label: "Lang & Heyne", value:  249},
  { label: "Laurent Ferrier", value:  250},
  { label: "Lebeau-Courally", value:  251},
  { label: "Lemania", value:  252},
  { label: "Leonidas", value:  253},
  { label: "Limes", value:  254},
  { label: "Lindburgh + Benson", value:  255},
  { label: "Linde Werdelin", value:  256},
  { label: "Lip", value:  257},
  { label: "Liv Watches", value:  258},
  { label: "Locman", value:  259},
  { label: "Longines", value:  260},
  { label: "Longio", value:  261},
  { label: "Lorenz", value:  262},
  { label: "Lorus", value:  263},
  { label: "Louis Erard", value:  264},
  { label: "Louis Moinet", value:  265},
  { label: "Louis Vuitton", value:  266},
  { label: "Louis XVI", value:  267},
  { label: "Lucien Rochat", value:  268},
  { label: "Luminox", value:  269},
  { label: "M&M Swiss Watch", value:  270},
  { label: "Marcello C.", value:  271},
  { label: "Margi", value:  272},
  { label: "Marlboro", value:  273},
  { label: "Martin Braun", value:  274},
  { label: "Marvin", value:  275},
  { label: "Maserati", value:  276},
  { label: "Mathey-Tissot", value:  277},
  { label: "Mauboussin", value:  278},
  { label: "Maurice de Mauriac", value:  279},
  { label: "Maurice Lacroix", value:  280},
  { label: "Mb&f", value:  281},
  { label: "Meccaniche Veloci", value:  282},
  { label: "Meistersinger", value:  283},
  { label: "Mercure", value:  284},
  { label: "Meyers", value:  285},
  { label: "Michael Bittel", value:  286},
  { label: "Michael Kors", value:  287},
  { label: "Michel Herbelin", value:  288},
  { label: "Michel Jordi", value:  289},
  { label: "Michele", value:  290},
  { label: "Mido", value:  291},
  { label: "Milleret", value:  292},
  { label: "Milus", value:  293},
  { label: "Minerva", value:  294},
  { label: "Momentum", value:  295},
  { label: "Momo Design", value:  296},
  { label: "Mondaine", value:  297},
  { label: "Mondia", value:  298},
  { label: "Montano", value:  299},
  { label: "Montblanc", value:  300},
  { label: "Montega", value:  301},
  { label: "Morellato", value:  302},
  { label: "Moritz Grossmann", value:  303},
  { label: "Movado", value:  304},
  { label: "Mühle Glashütte", value:  305},
  { label: "N.B. Yäeger", value:  306},
  { label: "N.O.A", value:  307},
  { label: "Nautica", value:  308},
  { label: "Nauticfish", value:  309},
  { label: "Nike", value:  310},
  { label: "Nina Ricci", value:  311},
  { label: "Nivada", value:  312},
  { label: "Nivrel", value:  313},
  { label: "Nixon", value:  314},
  { label: "NOMOS", value:  315},
  { label: "Nouvelle Horlogerie Calabrese (NHC)", value:  316},
  { label: "ODM", value:  317},
  { label: "Officina del Tempo", value:  318},
  { label: "Ollech & Wajs", value:  319},
  { label: "Omega", value:  320},
  { label: "Orator", value:  321},
  { label: "Orbita", value:  322},
  { label: "Orfina", value:  323},
  { label: "Orient", value:  324},
  { label: "Oris", value:  325},
  { label: "Otumm", value:  326},
  { label: "Pacardt", value:  327},
  { label: "Panerai", value:  328},
  { label: "Parmigiani Fleurier", value:  329},
  { label: "Patek Philippe", value:  330},
  { label: "Paul Picot", value:  331},
  { label: "Pequignet", value:  332},
  { label: "Perigáum", value:  333},
  { label: "Perrelet", value:  334},
  { label: "Perseo", value:  335},
  { label: "Phantoms", value:  336},
  { label: "Philip Stein", value:  337},
  { label: "Philip Watch", value:  338},
  { label: "Piaget", value:  339},
  { label: "Pierre Balmain", value:  340},
  { label: "Pierre Cardin", value:  341},
  { label: "Pierre DeRoche", value:  342},
  { label: "Pierre Kunz", value:  343},
  { label: "Police", value:  344},
  { label: "Poljot", value:  345},
  { label: "Porsche Design", value:  346},
  { label: "Preisig Schaffhausen", value:  347},
  { label: "Prim", value:  348},
  { label: "Pro-Hunter", value:  349},
  { label: "Pryngeps", value:  350},
  { label: "Pulsar", value:  351},
  { label: "Puma", value:  352},
  { label: "Quinting", value:  353},
  { label: "Rado", value:  354},
  { label: "Raidillon", value:  355},
  { label: "Rainer Brand", value:  356},
  { label: "Rainer Nienaber", value:  357},
  { label: "Ralf Tech", value:  358},
  { label: "Ralph Lauren", value:  359},
  { label: "Raymond Weil", value:  360},
  { label: "Rebellion", value:  361},
  { label: "Ressence", value:  362},
  { label: "Revue Thommen", value:  363},
  { label: "RGM", value:  364},
  { label: "Richard Mille", value:  365},
  { label: "Rios1931", value:  366},
  { label: "Roamer", value:  367},
  { label: "Roger Dubuis", value:  368},
  { label: "Rolex", value:  369},
  { label: "Rolf Lang", value:  370},
  { label: "Romain Jerome", value:  371},
  { label: "Rothenschild", value:  372},
  { label: "ROWI", value:  373},
  { label: "RSW", value:  374},
  { label: "Ryser Kentfield", value:  375},
  { label: "S.Oliver", value:  376},
  { label: "S.T. Dupont", value:  377},
  { label: "Salvatore Ferragamo", value:  378},
  { label: "Sarcar", value:  379},
  { label: "Scalfaro", value:  380},
  { label: "Schaumburg", value:  381},
  { label: "Schwarz Etienne", value:  382},
  { label: "Sea-Gull", value:  383},
  { label: "Sector", value:  384},
  { label: "Seiko", value:  385},
  { label: "Sevenfriday", value:  386},
  { label: "Shinola", value:  387},
  { label: "Sinn", value:  388},
  { label: "Skagen", value:  389},
  { label: "Snyper", value:  390},
  { label: "Sothis", value:  391},
  { label: "Speake-Marin", value:  392},
  { label: "Squale", value:  393},
  { label: "St. Gallen", value:  394},
  { label: "Starkiin", value:  395},
  { label: "Steelcraft", value:  396},
  { label: "Steinhart", value:  397},
  { label: "Stowa", value:  398},
  { label: "Strom", value:  399},
  { label: "Stuhrling", value:  400},
  { label: "Swatch", value:  401},
  { label: "Swiss Military", value:  402},
  { label: "TAG Heuer", value:  403},
  { label: "Tavannes", value:  404},
  { label: "TB Buti", value:  405},
  { label: "Technomarine", value:  406},
  { label: "Technos", value:  407},
  { label: "Temption", value:  408},
  { label: "Tempvs Compvtare", value:  409},
  { label: "Tendence", value:  410},
  { label: "Terra Cielo Mare", value:  411},
  { label: "Theorein", value:  412},
  { label: "Thomas Ninchritz", value:  413},
  { label: "Thorr", value:  414},
  { label: "Tiffany", value:  415},
  { label: "Timberland Watches", value:  416},
  { label: "Timex", value:  417},
  { label: "Tissot", value:  418},
  { label: "Tokyo Flash", value:  419},
  { label: "Tommy Hilfiger", value:  420},
  { label: "Tonino Lamborghini", value:  421},
  { label: "Traser", value:  422},
  { label: "Tudor", value:  423},
  { label: "Tutima", value:  424},
  { label: "TW Steel", value:  425},
  { label: "U-Boat", value:  426},
  { label: "Ulysse Nardin", value:  427},
  { label: "Unikatuhren", value:  428},
  { label: "Union Glashütte", value:  429},
  { label: "Universal Genève", value:  430},
  { label: "Urban Jürgensen", value:  431},
  { label: "Urwerk", value:  432},
  { label: "Vacheron Constantin", value:  433},
  { label: "Valbray", value:  434},
  { label: "Valentino", value:  435},
  { label: "Van Cleef & Arpels", value:  436},
  { label: "Van Der Bauwede", value:  437},
  { label: "Vangarde", value:  438},
  { label: "Ventura", value:  439},
  { label: "Versace", value:  440},
  { label: "Vianney Halter", value:  441},
  { label: "Viceroy", value:  442},
  { label: "Victorinox Swiss Army", value:  443},
  { label: "Villemont", value:  444},
  { label: "Vincent Calabrese", value:  445},
  { label: "Vixa", value:  446},
  { label: "Vogard", value:  447},
  { label: "Vollmer", value:  448},
  { label: "Volna", value:  449},
  { label: "Vostok", value:  450},
  { label: "Voutilainen", value:  451},
  { label: "Vulcain", value:  452},
  { label: "Wakmann", value:  453},
  { label: "Waltham", value:  454},
  { label: "Welder", value:  455},
  { label: "Wempe", value:  456},
  { label: "Wenger", value:  457},
  { label: "Werenbach", value:  458},
  { label: "Wittnauer", value:  459},
  { label: "Wyler", value:  460},
  { label: "Wyler Vetta", value:  461},
  { label: "Xemex", value:  462},
  { label: "Yantar", value:  463},
  { label: "Yes Watch", value:  464},
  { label: "Yves Saint Laurent", value:  465},
  { label: "Zeitwinkel", value:  466},
  { label: "Zenith", value:  467},
  { label: "Zeno-Watch Basel", value:  468},
  { label: "ZentRa", value:  469},
  { label: "Zeppelin", value:  470},
  { label: "Zodiac", value:  471}]

export default brandsJson